---
- name: Install Zsh dependencies
  ansible.builtin.apt:
    name:
      - zsh
      - git
      - curl
    state: present
    update_cache: true

- name: Clone or update Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ target_home }}/.oh-my-zsh"
    version: master
    depth: 1
    update: true

- name: Own Oh My Zsh files
  ansible.builtin.file:
    path: "{{ target_home }}/.oh-my-zsh"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    recurse: true
  failed_when: false

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /usr/bin/zsh
  when: target_user != 'root'
